# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e997b404676e1f24fb893c30072a93a1e6712cf0d27e3279d9be1cc3e96e9eb8c244cc0c4a4103d0ce83088fb40faa4752d34359991f5afe22acd444cde500be

test:
  secret_key_base: 976118ea24698f63957e62ece26c776ebbe181172d4e2ce9fe65629608b49b79512d26b21aba918efdc538c81cb7ffd4f2cbd7aea63fceddcd61e9ea9e73c642

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
